import { query, mutation } from "./_generated/server";
import { v } from "convex/values";

export const list = query({
  args: {},
  handler: async (ctx) => {
    return await ctx.db.query("dives").order("desc").collect();
  },
});

export const get = query({
  args: { id: v.id("dives") },
  handler: async (ctx, args) => {
    return await ctx.db.get(args.id);
  },
});

export const create = mutation({
  args: {
    siteName: v.string(),
    date: v.string(),
    location: v.string(),
    maxDepth: v.number(),
    duration: v.number(),
    visibility: v.number(),
    waterTemp: v.number(),
    buddyName: v.string(),
    marineLife: v.array(
      v.object({
        id: v.optional(v.string()),
        name: v.string(),
        scientificName: v.optional(v.string()),
        imageUrl: v.optional(v.string()),
        custom: v.optional(v.boolean()),
      })
    ),
    notes: v.string(),
    photos: v.array(v.string()),
    createdAt: v.string(),
  },
  handler: async (ctx, args) => {
    const id = await ctx.db.insert("dives", args);
    return id;
  },
});

export const update = mutation({
  args: {
    id: v.id("dives"),
    siteName: v.string(),
    date: v.string(),
    location: v.string(),
    maxDepth: v.number(),
    duration: v.number(),
    visibility: v.number(),
    waterTemp: v.number(),
    buddyName: v.string(),
    marineLife: v.array(
      v.object({
        id: v.optional(v.string()),
        name: v.string(),
        scientificName: v.optional(v.string()),
        imageUrl: v.optional(v.string()),
        custom: v.optional(v.boolean()),
      })
    ),
    notes: v.string(),
    photos: v.array(v.string()),
    createdAt: v.string(),
  },
  handler: async (ctx, args) => {
    const { id, ...rest } = args;
    await ctx.db.replace(id, rest);
  },
});

export const remove = mutation({
  args: { id: v.id("dives") },
  handler: async (ctx, args) => {
    await ctx.db.delete(args.id);
  },
});

const SAMPLE_DIVES = [
  {
    siteName: "Blue Hole",
    date: "2024-03-15",
    location: "Lighthouse Reef, Belize",
    maxDepth: 40,
    duration: 42,
    visibility: 30,
    waterTemp: 26,
    buddyName: "Sarah",
    marineLife: [
      { id: "1", name: "Reef Shark", scientificName: "Carcharhinus melanopterus", custom: false },
      { id: "41", name: "Giant Grouper", scientificName: "Epinephelus lanceolatus", custom: false },
      { id: "5", name: "Nurse Shark", scientificName: "Ginglymostoma cirratum", custom: false },
    ],
    notes: "Incredible dive! The stalactites at 40m were mesmerizing. Saw a massive groupers stationary at the edge.",
    photos: [],
    createdAt: "2024-03-15T14:30:00Z",
  },
  {
    siteName: "Great Blue Hole",
    date: "2024-02-28",
    location: "Lighthouse Reef, Belize",
    maxDepth: 35,
    duration: 38,
    visibility: 25,
    waterTemp: 27,
    buddyName: "Mike",
    marineLife: [
      { name: "Reef Shark", custom: true },
      { name: "Jack", custom: true },
      { name: "Sea Turtle", custom: true },
    ],
    notes: "Crystal clear conditions. Multiple reef sharks circling the edge.",
    photos: [],
    createdAt: "2024-02-28T10:15:00Z",
  },
  {
    siteName: "Thistlegorm",
    date: "2024-06-20",
    location: "Red Sea, Egypt",
    maxDepth: 30,
    duration: 65,
    visibility: 20,
    waterTemp: 24,
    buddyName: "Ahmed",
    marineLife: [
      { name: "Barracuda", custom: true },
      { name: "Batfish", custom: true },
      { id: "91", name: "Moray Eel", scientificName: "Gymnothorax javanicus", custom: false },
    ],
    notes: "Wreck diving at its finest. The motorbikes and trucks are still visible.",
    photos: [],
    createdAt: "2024-06-20T09:00:00Z",
  },
  {
    siteName: "Yongala",
    date: "2024-05-10",
    location: "Townsville, Australia",
    maxDepth: 18,
    duration: 55,
    visibility: 15,
    waterTemp: 23,
    buddyName: "Jenna",
    marineLife: [
      { id: "21", name: "Manta Ray", scientificName: "Manta birostris", custom: false },
      { id: "31", name: "Sea Turtle", scientificName: "Chelonia mydas", custom: false },
      { name: "Trevalley", custom: true },
    ],
    notes: "Manta cleaning station - saw 4 mantas! The wreck is completely covered in soft coral.",
    photos: [],
    createdAt: "2024-05-10T11:30:00Z",
  },
  {
    siteName: "Silfra Fissure",
    date: "2024-01-05",
    location: "Thingvellir, Iceland",
    maxDepth: 18,
    duration: 35,
    visibility: 100,
    waterTemp: 2,
    buddyName: "Erik",
    marineLife: [{ name: "Diving Snorkel Duck", custom: true }],
    notes: "Incredible visibility - over 100m! The water is 30+ years old, filtered through volcanic rock.",
    photos: [],
    createdAt: "2024-01-05T13:00:00Z",
  },
  {
    siteName: "Ribbon Reef 10",
    date: "2024-04-02",
    location: "Great Barrier Reef, Australia",
    maxDepth: 25,
    duration: 48,
    visibility: 35,
    waterTemp: 24,
    buddyName: "Dave",
    marineLife: [
      { id: "2", name: "Whitetip Shark", scientificName: "Triaenodon obesus", custom: false },
      { id: "74", name: "Giant Trevally", scientificName: "Caranx ignobilis", custom: false },
      { id: "51", name: "Clownfish", scientificName: "Amphiprion ocellaris", custom: false },
    ],
    notes: "Drift dive along the wall. GTT followed us for 5 minutes - incredible experience.",
    photos: [],
    createdAt: "2024-04-02T08:45:00Z",
  },
  {
    siteName: "Daedalus",
    date: "2024-07-12",
    location: "Red Sea, Egypt",
    maxDepth: 35,
    duration: 52,
    visibility: 30,
    waterTemp: 26,
    buddyName: "Youssef",
    marineLife: [
      { name: "Oceanic Whitetip", custom: true },
      { id: "101", name: "Dolphin", scientificName: "Delphinus delphis", custom: false },
      { id: "111", name: "Mola Mola", scientificName: "Mola mola", custom: false },
    ],
    notes: "Long deep dive. Oceanics at the safety stop! A dolphin passed by on the surface.",
    photos: [],
    createdAt: "2024-07-12T07:30:00Z",
  },
  {
    siteName: "Manta Night Dive",
    date: "2024-08-25",
    location: "Kona, Hawaii",
    maxDepth: 12,
    duration: 75,
    visibility: 20,
    waterTemp: 25,
    buddyName: "Kai",
    marineLife: [
      { id: "21", name: "Manta Ray", scientificName: "Manta birostris", custom: false },
      { id: "23", name: "Eagle Ray", scientificName: "Myliobatis californica", custom: false },
    ],
    notes: "Night dive with 8 mantas circling the lights. They came within inches.",
    photos: [],
    createdAt: "2024-08-25T21:00:00Z",
  },
  {
    siteName: "Palau Blue Corner",
    date: "2024-09-14",
    location: "Palau, Micronesia",
    maxDepth: 28,
    duration: 55,
    visibility: 40,
    waterTemp: 29,
    buddyName: "Tino",
    marineLife: [
      { name: "Shark", custom: true },
      { id: "23", name: "Eagle Ray", scientificName: "Myliobatis californica", custom: false },
      { id: "74", name: "Giant Trevally", scientificName: "Caranx ignobilis", custom: false },
    ],
    notes: "Drift dive at the famous corner. Sharks patrolling the reef wall.",
    photos: [],
    createdAt: "2024-09-14T07:00:00Z",
  },
  {
    siteName: "Crystal Bay",
    date: "2024-11-18",
    location: "Nusa Penida, Bali",
    maxDepth: 35,
    duration: 45,
    visibility: 20,
    waterTemp: 27,
    buddyName: "Wayan",
    marineLife: [
      { id: "111", name: "Mola Mola", scientificName: "Mola mola", custom: false },
      { id: "21", name: "Manta Ray", scientificName: "Manta birostris", custom: false },
    ],
    notes: "Mola season! Current was intense but saw 3 molas. Cold water bringing nutrients.",
    photos: [],
    createdAt: "2024-11-18T08:15:00Z",
  },
  {
    siteName: "SSRK Liberty",
    date: "2024-12-05",
    location: "Tulamben, Bali",
    maxDepth: 18,
    duration: 50,
    visibility: 15,
    waterTemp: 28,
    buddyName: "Made",
    marineLife: [
      { name: "Pygmy Seahorse", custom: true },
      { name: "Frogfish", custom: true },
      { name: "Ghost Pipefish", custom: true },
    ],
    notes: "Muck diving at its best. Found 3 different seahorses on the gorgonian fans.",
    photos: [],
    createdAt: "2024-12-05T14:00:00Z",
  },
  {
    siteName: "Wolf Island",
    date: "2025-01-20",
    location: "Galapagos, Ecuador",
    maxDepth: 30,
    duration: 55,
    visibility: 25,
    waterTemp: 22,
    buddyName: "Carlos",
    marineLife: [
      { name: "Hammerhead", custom: true },
      { name: "Sea Lion", custom: true },
      { name: "Marine Iguana", custom: true },
    ],
    notes: "Hammerhead school of 50+ at the cleaning station! Sea lions playing in the bubbles.",
    photos: [],
    createdAt: "2025-01-20T07:30:00Z",
  },
  {
    siteName: "Darwin's Arch",
    date: "2025-01-22",
    location: "Darwin Island, Galapagos",
    maxDepth: 28,
    duration: 48,
    visibility: 30,
    waterTemp: 23,
    buddyName: "Jorge",
    marineLife: [
      { name: "Hammerhead", custom: true },
      { name: "Giant Tortoise", custom: true },
      { name: "Booby", custom: true },
    ],
    notes: "Hammerheads everywhere - hundreds! Currents pulling through the arch.",
    photos: [],
    createdAt: "2025-01-22T09:00:00Z",
  },
  {
    siteName: "Osprey Reef",
    date: "2025-02-10",
    location: "Coral Sea, Australia",
    maxDepth: 40,
    duration: 52,
    visibility: 35,
    waterTemp: 26,
    buddyName: "Luke",
    marineLife: [
      { name: "Grey Reef Shark", custom: true },
      { name: "Tuna", custom: true },
      { name: "Jacks", custom: true },
    ],
    notes: "Deep dive on the North Horn. Grey reef sharks circling. Huge tuna following us.",
    photos: [],
    createdAt: "2025-02-10T08:00:00Z",
  },
  {
    siteName: "Raja Ampat",
    date: "2025-03-05",
    location: "West Papua, Indonesia",
    maxDepth: 22,
    duration: 65,
    visibility: 30,
    waterTemp: 29,
    buddyName: "Rendy",
    marineLife: [
      { name: "Wobbegong", custom: true },
      { name: "Pajama Cardinalfish", custom: true },
      { name: "Seahorse", custom: true },
    ],
    notes: "Biodiversity hotspot. 20+ species in one photo! Wobbegong resting under a coral ledge.",
    photos: [],
    createdAt: "2025-03-05T10:15:00Z",
  },
  {
    siteName: "Fiji White Rock",
    date: "2025-03-20",
    location: "Beqa Lagoon, Fiji",
    maxDepth: 28,
    duration: 58,
    visibility: 25,
    waterTemp: 27,
    buddyName: "Semisi",
    marineLife: [
      { name: "Bull Shark", custom: true },
      { name: "Tiger Shark", custom: true },
      { name: "Lemon Shark", custom: true },
    ],
    notes: "Shark dive! Bull sharks with Tiger joined. 12+ sharks circling.",
    photos: [],
    createdAt: "2025-03-20T07:45:00Z",
  },
  {
    siteName: "MV Olympia",
    date: "2025-04-08",
    location: "Key Largo, Florida",
    maxDepth: 35,
    duration: 45,
    visibility: 20,
    waterTemp: 24,
    buddyName: "Mark",
    marineLife: [
      { name: "Goliath Grouper", custom: true },
      { name: "Barracuda", custom: true },
      { name: "Turtle", custom: true },
    ],
    notes: "Wreck penetration. Goliath grouper guarding the wheelhouse. Barracuda school at the mooring line.",
    photos: [],
    createdAt: "2025-04-08T11:00:00Z",
  },
  {
    siteName: "Blue Corner Wall",
    date: "2025-04-15",
    location: "Kohekele, Hawaii",
    maxDepth: 25,
    duration: 50,
    visibility: 35,
    waterTemp: 24,
    buddyName: "Keoni",
    marineLife: [
      { id: "21", name: "Manta Ray", custom: false },
      { name: "White Tip Shark", custom: true },
    ],
    notes: "Drift dive along the wall. Manta appeared at the cleaning station.",
    photos: [],
    createdAt: "2025-04-15T09:30:00Z",
  },
  {
    siteName: "Batu Bolong",
    date: "2025-05-02",
    location: "Komodo, Indonesia",
    maxDepth: 30,
    duration: 60,
    visibility: 25,
    waterTemp: 27,
    buddyName: "Putu",
    marineLife: [
      { name: "Reef Shark", custom: true },
      { name: "Turtle", custom: true },
      { name: "Giant Trevally", custom: true },
    ],
    notes: "Currents were strong but saw a turtle and reef shark. Great coral coverage.",
    photos: [],
    createdAt: "2025-05-02T08:00:00Z",
  },
  {
    siteName: "Shark Bay",
    date: "2025-05-18",
    location: "Exmouth, Australia",
    maxDepth: 20,
    duration: 45,
    visibility: 15,
    waterTemp: 22,
    buddyName: "Liam",
    marineLife: [
      { name: "Whale Shark", custom: true },
      { name: "Manta Ray", custom: true },
      { name: "Sea Snake", custom: true },
    ],
    notes: "Whale shark season! One passed within 3 meters - unforgettable experience.",
    photos: [],
    createdAt: "2025-05-18T14:00:00Z",
  },
];

export const seed = mutation({
  args: {},
  handler: async (ctx) => {
    for (const dive of SAMPLE_DIVES) {
      await ctx.db.insert("dives", dive);
    }
    return SAMPLE_DIVES.length;
  },
});